# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB='postgres-production'
ENV POSTGRES_USER='eric'
ENV POSTGRES_PASSWORD='Eric@4999'

# Create a directory to store the database data
RUN mkdir -p /var/lib/postgresql/data

# Set the directory as a volume
VOLUME /var/lib/postgresql/data

# Expose the default PostgreSQL port
EXPOSE 5432
# You can add additional configurations or scripts if needed

# For example, you can copy SQL scripts to initialize the database schema
# CMD instruction to start PostgreSQL when the container runs
CMD ["postgres"]
